// Generated by CoffeeScript 1.9.2
var Queue, async;

Queue = require('seuss-queue');

async = require('odo-async');

module.exports = function(options) {
  var _currentbackoff, _drain, _inprogress, _retry, backoff, inflight, onitem, retrying, retrytimeout;
  onitem = options.onitem;
  inflight = options.inflight;
  if (inflight == null) {
    inflight = Queue();
  }
  retrying = options.retrying;
  if (retrying == null) {
    retrying = Queue();
  }
  backoff = options.delay;
  if (backoff == null) {
    backoff = 500;
  }
  retrytimeout = null;
  _inprogress = false;
  _currentbackoff = backoff;
  _retry = function() {
    var all, i, item, len;
    _currentbackoff *= 2;
    all = retrying.all();
    for (i = 0, len = all.length; i < len; i++) {
      item = all[i];
      inflight.enqueue(item);
    }
    retrying = Queue();
    if (!_inprogress) {
      return _drain();
    }
  };
  _drain = function() {
    var item;
    _inprogress = true;
    if (inflight.length() === 0) {
      if (retrying.length() === 0) {
        _currentbackoff = backoff;
      }
      if (retrytimeout === null) {
        console.log("Retrying " + (retrying.length()) + " messages in " + _currentbackoff + "ms");
        retrytimeout = setTimeout(_retry, _currentbackoff);
      }
      _inprogress = false;
      return;
    }
    item = inflight.peek();
    return item(function(success) {
      if (!success) {
        retrying.enqueue(item);
      }
      inflight.dequeue();
      return async.delay(_drain);
    });
  };
  return {
    enqueue: function(item, cb) {
      inflight.enqueue(item);
      if (!_inprogress) {
        return _drain();
      }
    },
    inflight: function() {
      return inflight.all();
    },
    retrying: function() {
      return retrying.all();
    },
    all: function() {
      return [].concat(retrying.all()).concat(inflight.all());
    },
    length: function() {
      return inflight.length() + retrying.length();
    },
    compact: function() {
      inflight.compact();
      return retrying.compact();
    }
  };
};
